import './js/renderAbout';
import './js/renderProjects';
import './js/renderWorkExperience';
import './js/renderFurtherEducation';
import './js/renderInternship';
// import './js/renderEducation';
import './js/renderSkills';
import './js/renderLanguages';
import './js/renderContacts';
// import './js/renderAdditions';
import './js/renderAdditionsSidebar';
import './js/renderEducationSidebar';
import './js/downloadPdf';
import './js/openPdf';